### ISSUE TITLE
Creation of Multiple Links Representation should be based on RelationType and not on number of elements of that type

### ISSUE THREAD

**Issue by nilsschmidthamburg** [otto-de/edison-hal#11]
Due to
https://github.com/otto-de/edison-hal/blob/945c37cc9b70efba71dff8af6363ce909fd95696/src/main/java/de/otto/edison/hal/Links.java#L480
it is currently not possible to have a link relation type (other than curries) that should be represented as a multiple, if there are less than two elements of that relation type.

Example: 
The custom link relation type "myType" should allow multiples.
```
HalRepresentation.withLinks(
   Link.link("myRelationType", "http://www.example.com/myResource/1"),
   Link.link("myRelationType", "http://www.example.com/myResource/1"))
/* Will produce:
...
"_links": {
  "myRelationType": [
    {
      "href":"http://www.example.com/myResource/1"
    },
    {
      "href":"http://www.example.com/myResource/2"
    }
  ]
}
...
*/

HalRepresentation.withLinks(
    Link.link("myRelationType", "http://www.example.com/myResource/1")) 
/* Will produce:
...
"_links": {
  "myRelationType": {
      "href":"http://www.example.com/myResource/1"
    }
}
...
Should produce: 

...
"_links": {
  "myRelationType": [
    {
      "href":"http://www.example.com/myResource/1"
    }
  ]
}
...
*/
```

**Comment by gsteinacker** [comment]
According to the specification, the current behavior is correct: https://tools.ietf.org/html/draft-kelly-json-hal-08#section-4.1.1
The special curies link relation type is special, as they always have a list of links. This is inconsistent to other links - but all examples that I have found so far (incl. the spec) do it this way...

**Comment by nilsschmidthamburg** [comment]
The way I read the spec, it allows to define the values of properties within _links to be either a Link or an Array of Links, but not both at the same time.  

Comparing "Representing Multiple Links With The Same Relation" in http://stateless.co/hal_specification.html it is my understanding that for one particular linkrelation type (within a given object of a specific profile) you must decide to go with either an Array or a plain Object. But you have to make that decision and than stick with it (or break the interface).

That is also why the curries property always contains an Array, as there might be more than one Link object within.

**Comment by gsteinacker** [comment]
Sounds reasonable ;-)
I will have a look at it.

**Comment by gsteinacker** [comment]
Added
 - Links#linkingTo(List<Link>, Set<String>)
- Links.withArrayRels(Set<String>)
- Links.withArrayRels(String...)
- Links.Builder.withArrayRels(Set<String>)
- Links.Builder.withArrayRels(String...)
Please let me know, if something is missing or if you find a better solution.
