### ISSUE TITLE
Globally outputting null values of hal represenations

### ISSUE THREAD

**Issue by marceloverdijk** [otto-de/edison-hal#20]
`HalRepresentation` has a `@JsonInclude(NON_NULL)` annotation which causes to not include `null` properties of resources.

It would be nice to switch off this behaviour globally.

That said I can imagine that e.g. `_embedded` is not desired to be outputted when `null`.
Maybe it's better to move the `@JsonInclude(NON_NULL)` to particular fields of `HalRepresentation`?

**Comment by gsteinacker** [comment]
Once again you are right. As this should be easy to fix, I will do this in the next few days.
Not only _embedded - also the _links section should not be generated if there are no links; but maybe this should be configurable.

Thanks a lot for your bug reports!

**Comment by gsteinacker** [comment]
Solved in de.otto.edison:edison-hal:2.0.0-m2-SNAPSHOT
Will be released together with issue #21 as de.otto.edison:edison-hal:2.0.0-m2 soon
