### ISSUE TITLE
Next page computed wrong in zero based paging

### ISSUE THREAD

**Issue by pfeuffer** [otto-de/edison-hal#24]
In `NumberedPaging` the flag `hasMore` is computed wrong for zero based paging. Therefore the next page link is rendered, even when there are no more pages.

**Comment by pfeuffer** [comment]
Created pull request #25 for this.

**Comment by guidosteinacker1969** [comment]
Thank you very much for your contribution!
I've just merged your fix & released it as  2.0.1

**Comment by pfeuffer** [comment]
Thanks for the quick release :smiley:
