### ISSUE TITLE
Deserialization of json string into HalRepresentation and subsequent serialization are not symmetrical

### ISSUE THREAD

**Issue by MarkLehmacherInvestify** [otto-de/edison-hal#29]
When I deserialize a json string into a HalRepresentation, I can observe that all attributes are deserialized correctly into the instances attributes map. However, those very same attributes are not serialized when subsequently serializing the instance to json string.

My use case is a proxy service which does some limited interpretation of HalRepresentations, before passing them on.

**Comment by MarkLehmacherInvestify** [comment]
I worked around this now by introducing a wrapper which basically takes links/embedded/attributes from the HalRepresentation and has a @JsonAnyGetter method for the attributes.

Before that, I tried to access an embedded representation using instance.getEmbedded().getItemsBy( "myRel", MyHalRepresentationSubtypeWithAnnotatedAttrsGetter.class ); which did not work, because apparently I have to use HalParser for this to work rather than starting from an existing HalRepresentation instance. That seems counterintuitive to me.

**Comment by guidosteinacker1969** [comment]
Hi Mark,
thank you for your comments. Ich will try to find a solution for the serialization of attributes, but as I have some more side-projects, this will take some time. However, if you would like to contribute a solution, I could quickly do a release.

Because of the HalParser: you are right, that you need to use it, if you want to get embedded items with a custom type. I did not find a better solution yet, but I am very open for recommendations!

**Comment by JoaoCamposFrom94** [comment]
Hi, just want to say that in my current project we also hit this obstacle.
Is there any news or resolution scheduled for the near future?
Also, @MarkLehmacherInvestify , would you mind sharing a sample project demonstrating the fix?

Thanks in advance.

**Comment by gsteinacker** [comment]
Hi, I am just working on a possible solution. Right now, serialization seems to work, but I can not figure out how to preserve the ordering of the attributes inside of a HalRepresentation. If you can live with this, I could quickly provide a fix that should work for this issue.

**Comment by JoaoCamposFrom94** [comment]
I'd like that please. The order of attributes is not important, we really just need the information.
If you do that I see no reason we won't use your library.

Thanks in advance @gsteinacker

**Comment by gsteinacker** [comment]
Issue is fixed in release 2.1.0. I also found a solution for the ordering of the attributes, should not be an issue anymore. Please give me some feedback whether or not everything is working as expected.

**Comment by JoaoCamposFrom94** [comment]
Thanks @gsteinacker, I confirm that our use case has been fixed. No need to use HalParser to create a proxy.
