### ISSUE TITLE
Add more / refactor existing examples

### ISSUE THREAD

**Issue by guidosteinacker1969** [otto-de/edison-hal#4]

**Comment by marceloverdijk** [comment]
Are you aware of any other samples using edison-hal? In particular using paged resource collections?

**Comment by gsteinacker** [comment]
Section 4.10 in README.md contains some example code on how to traverse over paged resources. If you need more, I can add an example in the next couple of days.

**Comment by marceloverdijk** [comment]
Hi @gsteinacker no need to add an example right now. I was talking about rendering pages resources (not parsing) but I think this can be done just like https://github.com/otto-de/edison-hal/blob/master/example-springboot/src/main/java/de/otto/edison/hal/example/web/ProductsHalJson.java.

**Comment by agebhar1** [comment]
Hi @guidosteinacker1969 extend [ReadmeExamples.java](https://github.com/otto-de/edison-hal/blob/master/src/test/java/de/otto/edison/hal/ReadmeExamples.java) by examples from _4.6 Parsing application/hal+json documents_ (Example_4_6_1 and Example_4_6_2 specially) would be really nice.

**Comment by guidosteinacker1969** [comment]
Thank you for your contribution; I have just merged your pull request.

**Comment by agebhar1** [comment]
You're welcome.
